project:
  type: website

website:
  title: "Third Year Labs - Ising Model"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: dummy.qmd
        text: "A dummy mage"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
